version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '200k'
    max-file: '5'
  driver: json-file

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    restart: always
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/minecraft.env
    ports:
    - 25565:25565
    volumes:
    - "${VOLUME_DIR}/minecraft:/data"
    tty: true
    stdin_open: true
networks:
  server-tools_media-server-net:
    external: true