version: '3'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    restart: always
    cap_add:
      - NET_ADMIN
    env_file:
    - env_files/common_envs.env
    - env_files/letsencrypt.env
    volumes:
      - /home/maxoumask/dev/media-server/volumes/letsencrypt/config:/config
    ports:
      - 80:80
      - 443:443

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    restart: on-failure
    env_file:
      - env_files/common_envs.env
    ports:
      - 9117:9117
    volumes:
      - "/home/maxoumask/dev/media-server/volumes/jackett/config:/config"
      - /etc/localtime:/etc/localtime:ro

  deluge:
    image: linuxserver/deluge:136 #upper version of the image are broken at the moment
    container_name: deluge
    hostname: deluge
    restart: on-failure
    env_file:
      - env_files/common_envs.env
      - env_files/deluge.env
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
    volumes:
      - "/home/maxoumask/dev/media-server/volumes/media/downloads:/downloads"
      - "/home/maxoumask/dev/media-server/volumes/deluge/config:/config"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    restart: on-failure
    env_file:
      - env_files/common_envs.env
    ports:
      - 8989:8989
    volumes:
    - "/home/maxoumask/dev/media-server/volumes/sonarr/config:/config"
    - "/home/maxoumask/dev/media-server/volumes/media/tv:/tv"
    - "/home/maxoumask/dev/media-server/volumes/media/downloads:/downloads"
    - /etc/localtime:/etc/localtime:ro

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    restart: on-failure
    env_file:
      - env_files/common_envs.env
    ports:
      - 7878:7878
    volumes:
      - "/home/maxoumask/dev/media-server/volumes/radarr/config:/config"
      - "/home/maxoumask/dev/media-server/volumes/media/downloads:/downloads"
      - "/home/maxoumask/dev/media-server/volumes/media/movies:/movies"
      - /etc/localtime:/etc/localtime:ro

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: radarr
    restart: on-failure
    env_file:
      - env_files/common_envs.env
      - env_files/plex.env
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5354:5353/udp"
      - "1901:1900/udp"
    volumes:
      - "/home/maxoumask/dev/media-server/volumes/plex/config:/config"
      - "/home/maxoumask/dev/media-server/volumes/media/tv:/data/tvshows"
      - "/home/maxoumask/dev/media-server/volumes/media/movies:/data/movies"
      - "/home/maxoumask/dev/media-server/volumes/plex/transcode:/transcode"


