version: '3'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    restart: always
    cap_add:
      - NET_ADMIN
    env_file:
    - env_files/common_envs.env
    - env_files/letsencrypt.env
    volumes:
      - /home/maxoumask/dev/media-server/volumes/letsencrypt/config:/config
    ports:
      - 80:80
      - 443:443


  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    restart: on-failure
    env_file:
      - env_files/common_envs.env
    ports:
      - 9117:9117
    volumes:
      - "/home/maxoumask/dev/media-server/volumes/jackett/config:/config"
      - /etc/localtime:/etc/localtime:ro

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    hostname: deluge
    restart: on-failure
#    network_mode: host
    env_file:
      - env_files/common_envs.env
      - env_files/deluge.env
    volumes:
      - "/home/maxoumask/dev/media-server/volumes/media:/downloads"
      - "/home/maxoumask/dev/media-server/volumes/deluge/config:/config"

#  plex:
#    depends_on:
#      - deluge
#    image: linuxserver/plex
#    container_name: plex
#    hostname: 'plex'
#    restart: on-failure
#    network_mode: host
#    volumes:
#      - "${VOLUME_PLEX}/database:/config"
#      - "${VOLUME_PLEX}/transcode:/transcode"
#      - "${VOLUME_DIR}/media/completed:/data"
#
#

#
#  couchpotato:
#    depends_on:
#      - deluge
#    image: linuxserver/couchpotato
#    container_name: couchpotato
#    hostname: couchpotato
#    restart: on-failure
#    environment:
#      - PUID=${MS_PUID}
#      - PGID=${MS_PGID}
#      - TZ=${MS_TZ}
#    ports:
#      - 5050:5050
#    volumes:
#      - "${VOLUME_DIR}/media/completed/movies:/downloads"
#      - "${VOLUME_COUCHPOTATO}/config:/config"
#      - "${VOLUME_COUCHPOTATO}/movies:/movies"

#  sonarr:
#    depends_on:
#      - jackett
#    image: linuxserver/sonarr
#    hostname: sonarr
#    container_name: sonarr
#    restart: on-failure
#    environment:
#      - PUID=${MS_PUID}
#      - PGID=${MS_PGID}
#      - TZ=${MS_TZ}
#    ports:
#      - 8989:8989
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - "${VOLUME_SONARR}/sonarr/config:/config"
#      - "${VOLUME_DIR}/media/completed/tv:/tv"
#      - "${VOLUME_DIR}/media/completed:/downloads"