version: '3'
services:
  plex:
    depends_on: 
      - deluge
    image: plexinc/pms-docker
    container_name: plex
    hostname: 'plex'
    restart: on-failure
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1800:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - "${VOLUME_PLEX}/database:/config"
      - "${VOLUME_PLEX}/transcode:/transcode"
      - "${VOLUME_DIR}/media/completed:/data"
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    hostname: deluge
    restart: on-failure
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946/tcp
      - 58946:58946/udp
    volumes:
      - "${VOLUME_DIR}/media:/downloads"
      - "${VOLUME_DELUGE}/config:/config"
  couchpotato:
    depends_on: 
      - deluge
    image: linuxserver/couchpotato
    container_name: couchpotato
    hostname: couchpotato
    restart: on-failure
    environment: 
      - PUID=${MS_PUID}
      - PGID=${MS_PGID}
      - TZ=${MS_TZ}
    ports:
      - 5050:5050
    volumes:
      - "${VOLUME_DIR}/media/completed/movies:/downloads"
      - "${VOLUME_COUCHPOTATO}/config:/config"
      - "${VOLUME_COUCHPOTATO}/movies:/movies"
  jackett:
    depends_on: 
      - couchpotato
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    restart: on-failure
    environment: 
      - PUID=${MS_PUID}
      - PGID=${MS_PGID}
      - TZ=${MS_TZ}
    ports:
      - 9117:9117
    volumes:
      - "${VOLUME_JACKETT}/config:/config"
      - "${VOLUME_DIR}/media/completed:/downloads"
      - /etc/localtime:/etc/localtime:ro
  sonarr:
    depends_on: 
      - jackett
    image: linuxserver/sonarr
    hostname: sonarr
    container_name: sonarr
    restart: on-failure
    environment: 
      - PUID=${MS_PUID}
      - PGID=${MS_PGID}
      - TZ=${MS_TZ}
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${VOLUME_SONARR}/sonarr/config:/config"
      - "${VOLUME_DIR}/media/completed/tv:/tv"
      - "${VOLUME_DIR}/media/completed:/downloads"