version: '3'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/maxoumask/dev/media-server/volumes/letsencrypt/config:/config
    ports:
      - 80:80
      - 443:443
    environment:
      - PGID=1000
      - PUID=1000
      - TZ="Europe/Paris"
      - EMAIL=hello@maxoumask.com
      - URL=maxoumask.com
      - SUBDOMAINS=jackett,deluge,radarr,tautulli,plex,sonarr,ombi,elk
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - STAGING=true

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    restart: on-failure
    environment:
    - PGID=1000
    - PUID=1000
    - TZ="Europe/Paris"
    ports:
      - 9117:9117
    volumes:
      - "/home/maxoumask/dev/media-server/volumes/jackett/config:/config"
      - /etc/localtime:/etc/localtime:ro

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    hostname: deluge
    restart: on-failure
    network_mode: host
    volumes:
      - "${VOLUME_DIR}/media:/downloads"
      - "${VOLUME_DELUGE}/config:/config"

#  plex:
#    depends_on:
#      - deluge
#    image: linuxserver/plex
#    container_name: plex
#    hostname: 'plex'
#    restart: on-failure
#    network_mode: host
#    volumes:
#      - "${VOLUME_PLEX}/database:/config"
#      - "${VOLUME_PLEX}/transcode:/transcode"
#      - "${VOLUME_DIR}/media/completed:/data"
#
#

#
#  couchpotato:
#    depends_on:
#      - deluge
#    image: linuxserver/couchpotato
#    container_name: couchpotato
#    hostname: couchpotato
#    restart: on-failure
#    environment:
#      - PUID=${MS_PUID}
#      - PGID=${MS_PGID}
#      - TZ=${MS_TZ}
#    ports:
#      - 5050:5050
#    volumes:
#      - "${VOLUME_DIR}/media/completed/movies:/downloads"
#      - "${VOLUME_COUCHPOTATO}/config:/config"
#      - "${VOLUME_COUCHPOTATO}/movies:/movies"

#  sonarr:
#    depends_on:
#      - jackett
#    image: linuxserver/sonarr
#    hostname: sonarr
#    container_name: sonarr
#    restart: on-failure
#    environment:
#      - PUID=${MS_PUID}
#      - PGID=${MS_PGID}
#      - TZ=${MS_TZ}
#    ports:
#      - 8989:8989
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - "${VOLUME_SONARR}/sonarr/config:/config"
#      - "${VOLUME_DIR}/media/completed/tv:/tv"
#      - "${VOLUME_DIR}/media/completed:/downloads"