version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '200k'
    max-file: '5'
  driver: json-file

services:

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    environment:
      - AUTO_UPDATE=true
    volumes:
      - "${VOLUME_DIR}/jackett/config:/config"
      - "${VOLUME_DIR}/media/downloads:/downloads"
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
      - ${ENVFILES_DIR}/common_envs.env
    volumes:
    - "${VOLUME_DIR}/sonarr/config:/config"
    - "${VOLUME_DIR}/media/tv:/tv"
    - "${VOLUME_DIR}/media/downloads:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
  
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    volumes:
    - "${VOLUME_DIR}/radarr/config:/config"
    - "${VOLUME_DIR}/media/downloads:/downloads"
    - "${VOLUME_DIR}/media/movies:/movies"
    ports:
      - 7878:7878
    restart: unless-stopped

    #  geoip-updater:
    #    image: crazymax/geoip-updater:latest
    #    volumes:
    #      - "${VOLUME_DIR}/geoip:/data"
    #    env_file:
    #      - "${ENVFILES_DIR}/common_envs.env"
    #      - "${ENVFILES_DIR}/geoip-updater.env"
    #    restart: always

  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    networks:
    - server-tools_media-server-net
    env_file:
      - "${ENVFILES_DIR}/common_envs.env"
      - "${ENVFILES_DIR}/rtorrent.env"
    expose:
      - "6881/udp"
      - "8000"
      - "8080"
      - "9000"
      - "50000"
    ports:
      - target: 6881
        published: 6881
        protocol: udp
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
      - target: 50000
        published: 50000
        protocol: tcp
    volumes:
      - "${VOLUME_DIR}/rtorrent:/data"
      - "${VOLUME_DIR}/media/downloads:/downloads"
      - "${VOLUME_DIR}/rtorrent/passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

  rtorrent-logs:
    image: bash
    command: bash -c 'tail -f /log/*.log'
    depends_on:
      - rtorrent
    volumes:
      - "${VOLUME_DIR}/rtorrent/log:/log"
    restart: always

networks:
  server-tools_media-server-net:
    external: true
