version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '200k'
    max-file: '5'
  driver: json-file

services:

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    environment:
      - AUTO_UPDATE=true
    volumes:
      - "${VOLUME_DIR}/jackett/config:/config"
      - "${VOLUME_DIR}/media/downloads:/downloads"
    ports:
      - 9117:9117
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    volumes:
    - "${VOLUME_DIR}/media/downloads:/downloads"
    - "${VOLUME_DIR}/deluge/config:/config"
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
      - ${ENVFILES_DIR}/common_envs.env
    volumes:
    - "${VOLUME_DIR}/sonarr/config:/config"
    - "${VOLUME_DIR}/media/tv:/tv"
    - "${VOLUME_DIR}/media/downloads:/downloads"
    - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    restart: unless-stopped
  
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    volumes:
    - "${VOLUME_DIR}/radarr/config:/config"
    - "${VOLUME_DIR}/media/downloads:/downloads"
    - "${VOLUME_DIR}/media/movies:/movies"
    - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    - ${ENVFILES_DIR}/plex.env
    ports:
    - "32400:32400"
    - "32400:32400/udp"
    - "32469:32469"
    - "32469:32469/udp"
    - "5354:5353/udp"
    - "1901:1900/udp"
    volumes:
    - "${VOLUME_DIR}/plex/config:/config"
    - "${VOLUME_DIR}/media/tv:/data/tv"
    - "${VOLUME_DIR}/media/movies:/data/movies"
    restart: unless-stopped

networks:
  server-tools_media-server-net:
    external: true