version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '200k'
    max-file: '5'
  driver: json-file

services:

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    restart: on-failure
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    ports:
    - 9117:9117
    volumes:
    - "${VOLUME_DIR}/jackett/config:/config"
    - /etc/localtime:/etc/localtime:ro

  deluge:
    image: linuxserver/deluge:136
    container_name: deluge
    hostname: deluge
    restart: on-failure
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    ports:
    - "8112:8112"
    - "58846:58846"
    - "58946:58946"
    - "58946:58946/udp"
    volumes:
    - "${VOLUME_DIR}/media/downloads:/downloads"
    - "${VOLUME_DIR}/deluge/config:/config"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    restart: on-failure
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    ports:
    - 8989:8989
    volumes:
    - "${VOLUME_DIR}/sonarr/config:/config"
    - "${VOLUME_DIR}/media/tv:/tv"
    - "${VOLUME_DIR}/media/downloads:/downloads"
    - /etc/localtime:/etc/localtime:ro

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    restart: on-failure
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    ports:
    - 7878:7878
    volumes:
    - "${VOLUME_DIR}/radarr/config:/config"
    - "${VOLUME_DIR}/media/downloads:/downloads"
    - "${VOLUME_DIR}/media/movies:/movies"
    - /etc/localtime:/etc/localtime:ro

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    restart: on-failure
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    - ${ENVFILES_DIR}/plex.env
    ports:
    - "32400:32400"
    - "32400:32400/udp"
    - "32469:32469"
    - "32469:32469/udp"
    - "5354:5353/udp"
    - "1901:1900/udp"
    volumes:
    - "${VOLUME_DIR}/plex/config:/config"
    - "${VOLUME_DIR}/media/tv:/data/tvshows"
    - "${VOLUME_DIR}/media/movies:/data/movies"
    - "${VOLUME_DIR}/plex/transcode:/transcode"

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    hostname: ombi
    restart: on-failure
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    ports:
    - "3579:3579"
    volumes:
    - "${VOLUME_DIR}/ombi/config:/config"

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    hostname: tautulli
    restart: on-failure
    logging: *default-logging
    networks:
    - server-tools_media-server-net
    env_file:
    - ${ENVFILES_DIR}/common_envs.env
    ports:
    - 8181:8181
    volumes:
    - "${VOLUME_DIR}/tautulli/config:/config"
    - "${VOLUME_DIR}/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro"
networks:
  server-tools_media-server-net:
    external: true