version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '200k'
    max-file: '5'
  driver: json-file

services:
  swag:
    logging: *default-logging
    image: lscr.io/linuxserver/swag
    container_name: swag
    networks:
      - media-server-net
    cap_add:
      - NET_ADMIN
    env_file:
      - ${ENVFILES_DIR}/common_envs.env
      - ${ENVFILES_DIR}/swag.env
    volumes:
      - ${VOLUME_DIR}/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    logging: *default-logging
    networks:
      - media-server-net
    env_file:
      - '${ENVFILES_DIR}/common_envs.env'
    ports:
      - '9443:9443'
      - '8000:8000'
      - '9000:9000'
    volumes:
      - '${VOLUME_DIR}/portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/localtime:/etc/localtime:ro'

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - media-server-net
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  netdata:
    image: titpetric/netdata
    container_name: netdata
    restart: unless-stopped
    logging: *default-logging
    networks:
      - media-server-net
    ports:
      - '19999:19999'
    cap_add:
      - SYS_PTRACE
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  media-server-net:
    driver: bridge