version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '200k'
    max-file: '5'
  driver: json-file

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    restart: always
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    env_file:
      - ${ENVFILES_DIR}/common_envs.env
      - ${ENVFILES_DIR}/letsencrypt.env
    volumes:
      - ${VOLUME_DIR}/letsencrypt/config:/config
    ports:
      - 80:80
      - 443:443

#  watchtower:
#    image: v2tec/watchtower
#    container_name: watchtower
#    restart: unless-stopped
#    logging: *default-logging
#    environment:
#      - TZ=${TZ}
#    network_mode: "bridge"
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    command: --schedule @midnight --cleanup


  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    logging: *default-logging
    network_mode: "bridge"
    env_file:
      - '${ENVFILES_DIR}/common_envs.env'
    ports:
      - '9000:9000'
    volumes:
      - '${VOLUME_DIR}/portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/localtime:/etc/localtime:ro'
    command: ${PORTAINERSTYLE} -H unix:///var/run/docker.sock

  netdata:
    image: titpetric/netdata
    container_name: netdata
    restart: unless-stopped
    logging: *default-logging
    network_mode: "bridge"
    ports:
      - '19999:19999'
    cap_add:
      - SYS_PTRACE
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'